const ROOT = location.pathname.includes('/pages/') ? '../' : './';
const pages = ['hub','store','open','inventory','match','marketplace','odds'];
const countries=['England','Brazil','France','Argentina','Spain','Germany','Portugal','Netherlands','USA','Mexico','Japan','Nigeria','Ghana','Morocco','Canada','Italy','Uruguay','Belgium','Croatia','Senegal'];
const names={common:['A. Reed','T. Brooks','M. Lane','D. Holt','L. King','R. Stone','J. Vale','K. Morris','S. Bell','N. Cross','C. Webb','P. Gray','B. Fox','H. Ward','E. Shaw','O. Miles'],silver:['E. Costa','R. Morgan','L. Silva','D. Parker','M. Rossi','A. Nunes','J. Carter','S. Ito','V. Mensah','Y. Tanaka','N. Davies','F. Gomez','I. Diallo','C. Muller','T. Okafor'],gold:['K. Mbappe','J. Bellingham','V. Junior','E. Haaland','P. Foden','B. Saka','L. Messi','C. Ronaldo','K. De Bruyne','H. Kane','R. Leao','L. Modric'],diamond:['World Cup Mbappe','Prime Messi','Prime Ronaldo','Golden Boot Haaland','Captain Bellingham','Legend Neymar','Finals Vini']};
const State={get username(){return sessionStorage.getItem('cl_username')||''},set username(v){sessionStorage.setItem('cl_username',v)},get lld(){return +(sessionStorage.getItem('cl_lld')||'750')},set lld(v){sessionStorage.setItem('cl_lld',Math.max(0,Math.round(v))) ;refreshNavbar()},get std(){return +(sessionStorage.getItem('cl_std_cases')||'3')},set std(v){sessionStorage.setItem('cl_std_cases',Math.max(0,Math.round(v)));refreshNavbar()},get rare(){return +(sessionStorage.getItem('cl_rare_cases')||'0')},set rare(v){sessionStorage.setItem('cl_rare_cases',Math.max(0,Math.round(v)));refreshNavbar()},get inv(){try{return JSON.parse(sessionStorage.getItem('cl_inventory')||'[]')}catch{return[]}},set inv(v){sessionStorage.setItem('cl_inventory',JSON.stringify(v));refreshNavbar()},get listings(){try{return JSON.parse(sessionStorage.getItem('cl_listings')||'[]')}catch{return[]}},set listings(v){sessionStorage.setItem('cl_listings',JSON.stringify(v))},get division(){return +(sessionStorage.getItem('cl_division')||'10')},set division(v){sessionStorage.setItem('cl_division',Math.max(1,Math.min(10,v)));refreshNavbar()},get wins(){return +(sessionStorage.getItem('cl_wins')||'0')},set wins(v){sessionStorage.setItem('cl_wins',v)}};
function requireLogin(){if(!State.username && location.pathname.includes('/pages/')) location.href='../index.html'}
function logout(){sessionStorage.clear();location.href=ROOT+'index.html'}
function refreshNavbar(){const el=document.querySelector('.nav'); if(!el)return; const active=(location.pathname.split('/').pop()||'index.html').replace('.html',''); el.innerHTML=`<a class="brand" href="${ROOT}pages/hub.html"><i></i><span>Looklist · Case League</span></a><div class="navlinks">${pages.map(p=>`<a class="${active===p?'active':''}" href="${ROOT}pages/${p}.html">${p[0].toUpperCase()+p.slice(1)}</a>`).join('')}</div><div class="chips"><span class="chip">Std <b>${State.std}</b></span><span class="chip">Rare <b>${State.rare}</b></span><span class="chip">◈ <b>${State.lld}</b> LLD</span><span class="chip">D${State.division}</span></div>`}
function shell(){document.body.insertAdjacentHTML('afterbegin','<div class="bg-orb orb1"></div><div class="bg-orb orb2"></div><nav class="nav"></nav>');refreshNavbar()}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),3100)}
function rarityClass(r){return r.toLowerCase()}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function rarityRoll(odds){let n=Math.random()*100,c=0; for(const [r,p] of odds){c+=p;if(n<=c)return r} return 'Common'}
function ratingFor(r){const ranges={Common:[58,72],Silver:[73,82],Gold:[83,91],Diamond:[92,99]};const [a,b]=ranges[r];return Math.floor(a+Math.random()*(b-a+1))}
function makePlayer(r){const rating=ratingFor(r), base=rating-8; const mod= r==='Diamond'?18:r==='Gold'?12:r==='Silver'?6:0; const name=pick(names[rarityClass(r)]); const stats={attack:clamp(base+rand(-8,10)+mod/3),defence:clamp(base+rand(-8,10)+mod/3),experience:clamp(base+rand(-6,12)+mod/3),flair:clamp(base+rand(-12,16)+mod/2)}; const value=suggestValue(r,rating);return {id:'CL-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),name,country:pick(countries),pos:pick(['ST','LW','RW','CAM','CM','CDM','CB','GK']),rarity:r,rating,...stats,value,acquired:new Date().toLocaleString()}}
function rand(a,b){return Math.floor(a+Math.random()*(b-a+1))} function clamp(n){return Math.max(30,Math.min(99,Math.round(n)))}
function suggestValue(r,rt){const base={Common:8,Silver:70,Gold:430,Diamond:3200}[r];const mult={Common:3,Silver:13,Gold:95,Diamond:950}[r];return Math.round(base+(rt-55)*mult+Math.random()*base)}
function openStandard(){let res=[]; for(let i=0;i<3;i++)res.push(makePlayer('Common')); res.push(makePlayer(rarityRoll([['Silver',82],['Gold',15],['Diamond',3]]))); for(let i=0;i<2;i++)res.push(makePlayer(rarityRoll([['Common',70],['Silver',22],['Gold',7],['Diamond',1]]))); return shuffle(res)}
function openRare(){let res=[]; for(let i=0;i<2;i++)res.push(makePlayer('Common')); for(let i=0;i<2;i++)res.push(makePlayer(rarityRoll([['Silver',86],['Gold',12],['Diamond',2]]))); for(let i=0;i<2;i++)res.push(makePlayer(rarityRoll([['Common',45],['Silver',38],['Gold',14],['Diamond',3]]))); return shuffle(res)}
function shuffle(a){return a.sort(()=>Math.random()-.5)}
function playerHTML(p,small=false){return `<div class="player-card ${rarityClass(p.rarity)}" data-id="${p.id}"><div class="silhouette">♟</div><div class="pc-top"><div class="rating">${p.rating}</div><span class="badge ${rarityClass(p.rarity)}">${p.rarity}</span></div><div class="pc-bottom"><div class="pc-name">${p.name}</div><div class="muted">${p.country} · ${p.pos}</div><div class="stats-mini"><span>ATK<br><b>${p.attack}</b></span><span>DEF<br><b>${p.defence}</b></span><span>EXP<br><b>${p.experience}</b></span><span>FLR<br><b>${p.flair}</b></span></div><div class="muted" style="margin-top:9px">◈ ${p.value} LLD</div></div></div>`}
function addInventory(items){State.inv=[...items,...State.inv]}
function buyCase(type,qty=1){const price=type==='std'?170:250; const total=price*qty;if(State.lld<total)return toast('Not enough LLD for this purchase.'); State.lld-=total; if(type==='std')State.std+=qty; else State.rare+=qty; toast(`Purchased ${qty} ${type==='std'?'Standard':'Rare'} case${qty>1?'s':''}.`)}
function listPlayer(id,price){let inv=State.inv; const p=inv.find(x=>x.id===id); if(!p)return; State.listings=[{...p,listedAt:Date.now(),price:+price||p.value,seller:State.username},...State.listings]; State.inv=inv.filter(x=>x.id!==id); toast('Player listed on marketplace.')} 
function buyListing(id){let listings=State.listings; const l=listings.find(x=>x.id===id); if(!l)return; if(State.lld<l.price)return toast('Not enough LLD.'); State.lld-=l.price; addInventory([{...l,id:'CL-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),seller:undefined}]); State.listings=listings.filter(x=>x.id!==id); toast(`Bought ${l.name}. Admin took 20% marketplace fee.`)}
function removeListing(id){const l=State.listings.find(x=>x.id===id); if(!l || l.seller!==State.username)return; addInventory([l]); State.listings=State.listings.filter(x=>x.id!==id);toast('Listing removed.')}
function seededListings(){if(State.listings.length)return; const seed=[]; for(let i=0;i<10;i++){let r=rarityRoll([['Common',30],['Silver',42],['Gold',23],['Diamond',5]]),p=makePlayer(r); p.price=Math.round(p.value*(1.05+Math.random()*.45)); p.seller=pick(['Maya','Leo','Zain','Ava','Noah']); seed.push(p)} State.listings=seed}
function teamPower(team){return team.reduce((s,p)=>s+p.attack*1.05+p.defence*.95+p.experience*.85+p.flair*.7+p.rating*1.3,0)}
function simulate(userTeam){const enemy=[makePlayer(rarityRoll([['Common',45],['Silver',38],['Gold',15],['Diamond',2]])),makePlayer(rarityRoll([['Common',45],['Silver',38],['Gold',15],['Diamond',2]])),makePlayer(rarityRoll([['Common',45],['Silver',38],['Gold',15],['Diamond',2]]))]; let up=teamPower(userTeam), ep=teamPower(enemy), us=0,es=0,log=[]; for(let m=1;m<=90;m++){let chance=(up/(up+ep))*0.12; if(Math.random()<chance){us++;log.push(`${m}' ${pick(userTeam).name} scores after a sharp ${pick(['counter attack','flair move','through ball','press'])}.`)} if(Math.random()<(ep/(up+ep))*0.105){es++;log.push(`${m}' Rival ${pick(enemy).name} equalises with a clean finish.`)} if(Math.random()<.035)log.push(`${m}' ${pick(['Big tackle','Close save','Post hit','VAR check','Crowd roars'])}.`)} let reward=0;if(us>es){reward=25+(11-State.division)*35; State.lld+=reward; State.wins+=1;if(State.wins%3===0 && State.division>1)State.division-=1}else if(us===es){reward=10+(11-State.division)*8;State.lld+=reward} return {enemy,us,es,log,reward}}
document.addEventListener('DOMContentLoaded',()=>{if(location.pathname.includes('/pages/')){requireLogin();shell()}});
